# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Celine Li
email: celine.li@gmx.net
description: >- # this means to ignore newlines until "baseurl:"
 Personal Website for sharing articles and thoughts with the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "celineli99.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  celineli99

# Build settings
theme: null
remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-pdf-embed
  - jekyll-avatar
  - jekyll-relative-links


# Adding a custom _pages/ directory
include: [_pages]
# Adding defaults:
defaults:
  - 
    scope: 
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  - 
    scope:
      type: pages
      path: _pages
    values: 
      is_post: false
      layout: default # the above defaults are equivalent to specifying manually, in each post, is_post: true and layout: post AND manually for each page "is_post: false and layout: default"
    
# Adding permalinks
permalink: /:year/:title.html
# Adding menu bar
menu:
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
  - title: Blog
    url: /blog/


# Enabling Google Analytics
google_analytics: G-XZ2JB1W4P5


# Changing colours and sidebar images
accent_image: /assets/img/sidebar.jpg
accent_color: rgb(0,191,255)
theme_color: rgb(0,191,255)

#Adding Author information
author: 
  name: Celine Li
  picture:
    path: /assets/img/avatar.jpg
  social:
    github: celineli99
    linkedin: https://www.linkedin.com/in/celineli99/
    email: mailto:celine.li@gmx.net

#Changing favicon
favicon: /assets/img/android-chrome-192x192.png
apple_touch_icon: /assets/img/apple-touch-icon.png

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
